// <auto-generated />
namespace DSG.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_data04 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_data04));
        
        string IMigrationMetadata.Id
        {
            get { return "202303201738345_update_data04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
